import { NextResponse } from "next/server";
import type { GeneratedPrompt } from "@/lib/types";

export const runtime = "nodejs";

// Export a generated prompt (or a bundle) into various agent-friendly formats.
// format: md | txt | json | claude | cursor
export async function POST(req: Request) {
  let body: any;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const format = (body?.format ?? "md") as string;
  const repo = body?.repoFullName ?? "repository";
  const prompts = (body?.prompts ?? []) as GeneratedPrompt[];
  if (!prompts.length) return NextResponse.json({ error: "No prompts to export" }, { status: 400 });

  const safe = repo.replace(/[^a-z0-9._-]+/gi, "-");
  let content = "";
  let filename = `gitvibe-${safe}`;
  let mime = "text/plain; charset=utf-8";

  switch (format) {
    case "json":
      content = JSON.stringify({ repo, generatedBy: "GitVibe", prompts }, null, 2);
      filename += ".json";
      mime = "application/json; charset=utf-8";
      break;
    case "claude":
      // CLAUDE.md style project memory
      content = `# CLAUDE.md\n\n> Generated by GitVibe for ${repo}\n\n${prompts
        .map((p) => `## ${p.title}\n\n${p.content}`)
        .join("\n\n---\n\n")}\n`;
      filename = "CLAUDE.md";
      mime = "text/markdown; charset=utf-8";
      break;
    case "cursor":
      // .cursorrules style
      content = prompts.map((p) => p.content).join("\n\n---\n\n");
      filename = ".cursorrules";
      break;
    case "txt":
      content = prompts.map((p) => `=== ${p.title} ===\n\n${p.content}`).join("\n\n");
      filename += ".txt";
      break;
    case "md":
    default:
      content = `# GitVibe export — ${repo}\n\n${prompts
        .map((p) => `## ${p.title}\n\n${p.content}`)
        .join("\n\n---\n\n")}\n`;
      filename += ".md";
      mime = "text/markdown; charset=utf-8";
      break;
  }

  return new NextResponse(content, {
    headers: {
      "Content-Type": mime,
      "Content-Disposition": `attachment; filename="${filename}"`,
    },
  });
}
